<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZA3ZLvh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZA3ZLvh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZA3ZLvh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZA3ZLvh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZA3ZLvh\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZA3ZLvh',
    'container.build_id' => 'e267cce5',
    'container.build_time' => 1638530392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZA3ZLvh');
