<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0FhSb6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0FhSb6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW0FhSb6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW0FhSb6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW0FhSb6\App_KernelDevDebugContainer([
    'container.build_hash' => 'W0FhSb6',
    'container.build_id' => '2cba9f68',
    'container.build_time' => 1638533631,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0FhSb6');
