<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2rxdwgx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2rxdwgx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2rxdwgx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2rxdwgx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2rxdwgx\App_KernelDevDebugContainer([
    'container.build_hash' => '2rxdwgx',
    'container.build_id' => '45153852',
    'container.build_time' => 1638534572,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2rxdwgx');
